export enum RoleName {
	ROLE_ADMIN = 'ROLE_ADMIN',
	ROLE_PROGRAM_MANAGER = 'ROLE_PROGRAM_MANAGER',
	ROLE_PROJECT_COORDINATOR = 'ROLE_PROJECT_COORDINATOR',
	ROLE_MODERATOR = 'ROLE_MODERATOR',
	ROLE_CUSTOMER_CARE_SPECIALIST = 'ROLE_CUSTOMER_CARE_SPECIALIST',
}
